# Trigger Page Build for https://github.com/AKSW/leipzig.dataweek.de
name: Trigger Page Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    name: "📦 Trigger Project Test"
    steps:
    - name: Invoke workflow in another repo
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: "Build Jekyll Page Preview for the Next Layout"
        repo: AKSW/leipzig.dataweek.de
        ref: next
        token: ${{ secrets.GH_ACCESS_TOKEN_FOR_TRIGGER }}
